---
name: build_the_docs_test

on:
  pull_request:
    branches:
      - master

jobs:
  btd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Generate diff files
        run: python3 docs/examples/preprocess.py
        shell: bash

      - name: Toggle skip error checks on generate_diffs.sh
        run: ./docs/examples/toggle_skip_generate_diffs_err_check.sh
        shell: bash

      - uses: buildthedocs/btd@67180e0ca49e3619f2475686946997cb4a478bc1
        with:
          token: ${{ github.token }}
          skip-deploy: true

      - uses: actions/upload-artifact@v4
        with:
          name: docs
          path: docs/_build/html
